src/users/views.py
from flask import Blueprint,redirect,render_template,url_for,flash,session,current_app,request
from src.users.forms import LoginForm,RegisterForm,CambiarPassForm
from src.models import Users, Historial
from flask_login import login_user,logout_user
from src.decorators import requires_admin
from src import db
from flask_login import login_required
from src import login_manager
import os
from werkzeug.security import generate_password_hash
from src.comando import ParamikoComando
users = Blueprint('users',__name__)

@login_manager.user_loader
def load_user(user_id):
    return Users.query.get(user_id)


@users.route('/')
@users.route('/login',methods=['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = Users.query.filter_by(username=username).first()
        if form.check_user(username) and user.check_password(password):
            login_user(user)

            session['username'] = user.username
            if session['username'] == os.environ.get('ADMIN'):
                next = request.args.get('next')
                if next == None or not next[0] == '/':
                    next = url_for('core.home', user=session['username'])
                    flash('Eres el administrador', 'dark')
                return redirect(next)
            next = request.args.get('next')
            if next == None or not next[0] == '/':
                next = url_for('core.home',user=session['username'])
                flash(f'Bienvenido {session["username"]}', 'info')
            return redirect(next)

        else:
            flash('Nombre de usuario o password incorrectos','warning')
            return render_template('login.html',form=form)
    return render_template('login.html',form=form)

@login_required
@users.route('/register',methods=['GET','POST'])
@requires_admin
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        user = Users(form.username.data,form.password.data)
        if form.check_user(user.username):
            flash('El nombre de usuario ya esta en uso','warning')
            return render_template('register.html',form=form)
        else:
            db.session.add(user)
            db.session.commit()
            flash('El usuario ha sido agregado satisfactoriamente','success')
            return redirect(url_for('.login'))
    return render_template('register.html',form=form)



@login_required
@users.route('/cambiarpass/<string:username>',methods=['GET','POST'])
def cambiarpass(username):

    form = CambiarPassForm()

    if form.validate_on_submit():
        user = Users.query.filter_by(username=username).first()
        old_password =  form.old_password.data

        if form.old_password.data == form.password.data:
            flash('El password nuevo no debe ser igual que el password viejo, porfavor intente denuevo.', 'danger')
            return redirect(url_for('core.home', user=session['username']))

        if user.check_password(old_password):
            Users.query.filter_by(username= username).update({Users.password_hash:generate_password_hash(form.password.data)
                                                              },synchronize_session=False)
            db.session.commit()
            flash('Password cambiado satisfactoriamente.','success')
            return redirect(url_for('core.home',user=session['username']))
        else:

            flash('El password viejo no es correcto, porfavor vuelva a intentarlo.','info')

    return render_template('cambiar_password.html',form=form)


@login_required
@users.route('/delete/<int:userid>')
@requires_admin
def delete(userid):
    user = Users.query.filter(Users.id == userid).first()
    db.session.delete(user)
    db.session.commit()
    flash('El usuario ha sido borrado', 'success')

    return redirect(url_for('.list'))

@login_required
@users.route('/users_list')
@requires_admin
def list():
    query = Users.query.filter(Users.username != os.environ.get('ADMIN'))
    return render_template('userslist.html',users=query)



@login_required
@users.route('/mensaje')
def mensaje():
    pass



@login_required
@users.route('/logout')
def logout():
    camara = ParamikoComando()
    camara.conectar()
    comando = 'camara.py off'
    camara.ejecutarcomando(comando, False)

    camara.client.close()

    logout_user()
    flash(f'Chau {session["username"]}', 'primary')
    for i in session:
        print(i)
        session[i] = ''

    return redirect(url_for('.login'))

@login_required
@users.route('/historial/<string:username>')
def historial(username):
    if username != os.environ.get('ADMIN'):
        query = Historial.query.filter(Historial.usuario == username)
        #query.order_by(Historial.id.desc()).all()
    else:
        query = Historial.query.order_by(Historial.id.desc())
        #query.order_by(Historial.id.desc()).first()
    return render_template('historial.html', historial = query)

src/templates/automatico.html
{% extends 'base.html' %}
{% block title %} AUTOMATICO {% endblock title %}

{% block content %}

<form class="range-field" method="POST">

<div class="card bg-dark mx-auto text-left text-white col-md-4">
    {{ form.hidden_tag() }}
<div class="card-footer border-warning" id="divtierra">
    <label for="tierra">Tierra</label>
    <input type="checkbox" id="tierra" name="tierra" checked>
</div>
<div class="card-footer border-warning" id="divhidro">
    <label for="hidro">Hidroponía</label>
    <input type="checkbox" id="hidro" name="hidro">
</div>
<div class="card-footer border-warning">
    <label for="horasluz">Horas de luz</label>
    <input type="range" id="horasluz" name="horasluz" value="1" min="1" max="24" oninput="outputIDluz.value = horasluz.value">
    <output name="salida" id="outputIDluz"></output>
</div>
<div class="card-footer border-warning">
    <label for="hum_min">Humedad mínima</label>
    <input type="range" id="hum_min" name="hum_min" value="50" min="1" max="100" oninput="outputIDhum_min.value = hum_min.value">
    <output name="salida" id="outputIDhum_min"></output>
</div>
<div class="card-footer border-warning">
    <label for="hum_max">Humedad máxima</label>
    <input type="range" id="hum_max" name="hum_max" value="80" min="1" max="100" oninput="outputIDhum_max.value = hum_max.value">
    <output name="salida" id="outputIDhum_max"></output>
</div>
<div class="card-footer border-warning">
    <label for="temp_min">Temperatura mínima</label>
    <input type="range" id="temp_min" name="temp_min" value="20" min="1" max="100" oninput="outputIDtemp_min.value = temp_min.value">
    <output name="salida" id="outputIDtemp_min"></output>
</div>
<div class="card-footer border-warning">
    <label for="temp_max">Temperatura máxima</label>
    <input type="range" id="temp_max" name="temp_max" value="30" min="1" max="100" oninput="outputIDtemp_max.value = temp_max.value">
    <output name="salida" id="outputIDtemp_max"></output>
</div>
<div class="card-footer border-warning">
    <label for="ph_min">pH mínimo</label>
    <input type="range" step="0.1" id="ph_min" name="ph_min" value="6.0" min="0.1" max="14" oninput="outputIDph_min.value = ph_min.value">
    <output name="salida" id="outputIDph_min"></output>
</div>
<div class="card-footer border-warning">
    <label for="ph_max">pH máximo</label>
    <input type="range" step="0.1" id="ph_max" name="ph_max" value="7.0" min="0.1" max="14" oninput="outputIDph_max.value = ph_max.value">
    <output name="salida" id="outputIDph_max"></output>
</div>
<div class="card-footer border-warning">
    <label for="ec_min">EC mínimo</label>
    <input type="range" step="0.1" id="ec_min" name="ec_min" value="0.5" min="0.1" max="1000" oninput="outputIDec_min.value = ec_min.value">
    <output name="salida" id="outputIDec_min"></output>
</div>
<div class="card-footer border-warning">
    <label for="ec_max">EC máximo</label>
    <input type="range" step="0.1" id="ec_max" name="ec_max" value="1.5" min="0.1" max="1000" oninput="outputIDec_max.value = ec_max.value">
    <output name="salida" id="outputIDec_max"></output>
</div>
<div class="card-footer border-warning" id="divsuelo1">
    <label for="hum_suelo">Humedad del suelo</label>
    <input type="checkbox" id="hum_suelo" name="hum_suelo">
</div>
<div class="card-footer border-warning" id="divriego1">
    <label for="riego_por_tiempo">Riego por tiempo</label>
    <input type="checkbox" id="riego_por_tiempo" name="riego_por_tiempo">
</div>
<div class="card-footer border-warning" id="divsuelo2">
    <label for="humedad_suelo">Humedad del suelo</label>
    <input type="range" id="humedad_suelo" name="humedad_suelo" value="50" min="0" max="100" oninput="outputIDhumedad_suelo.value = humedad_suelo.value">
    <output name="salida" id="outputIDhumedad_suelo"></output>
</div>
<div class="card-footer border-warning" id="divriego2">
    <label for="riego">Riego</label>
    <input type="range" id="riego" name="riego" value="1" min="1" max="24" oninput="outputIDriego.value = riego.value">
    <output name="salida" id="outputIDriego"></output>
</div>
<div class="card-footer border-warning" id="divriego3">
    <label for="cant_riego">Cantidad de riego</label>
    <input type="range" id="cant_riego" name="cant_riego" value="30" min="1" max="60" oninput="outputIDcant_riego.value = cant_riego.value">
    <output name="salida" id="outputIDcant_riego"></output>
</div>
<div class="card-footer border-warning">
    <label for="ventilador">Ventilador</label>
    <input type="range" id="ventilador" name="ventilador" value="1" min="1" max="24" oninput="outputIDventilador.value = ventilador.value">
    <output name="salida" id="outputIDventilador"></output>
</div>
<div class="card-footer border-warning">
    <label for="cantidad_ventilador">Cantidad de ventiladores</label>
    <input type="range" id="cantidad_ventilador" name="cantidad_ventilador" value="1" min="1" max="10" oninput="outputIDcantidad_ventilador.value = cantidad_ventilador.value">
    <output name="salida" id="outputIDcantidad_ventilador"></output>
</div>
<div class="card-footer border-warning">
    <label for="heater">Calentador</label>
    <input type="range" id="heater" name="heater" value="1" min="1" max="24" oninput="outputIDheater.value = heater.value">
    <output name="salida" id="outputIDheater"></output>
</div>
<div class="card-footer border-warning">
    <label for="cantidad_calentador">Cantidad de calentadores</label>
    <input type="range" id="cantidad_calentador" name="cantidad_calentador" value="1" min="1" max="10" oninput="outputIDcantidad_calentador.value = cantidad_calentador.value">
    <output name="salida" id="outputIDcantidad_calentador"></output>
</div>
<div class="card-footer border-warning">
    <label for="humidificador">Humidificador</label>
    <input type="range" id="humidificador" name="humidificador" value="1" min="1" max="24" oninput="outputIDhumidificador.value = humidificador.value">
    <output name="salida" id="outputIDhumidificador"></output>
</div>
<div class="card-footer border-warning">
    <label for="cantidad_humidificador">Cantidad de humidificadores</label>
    <input type="range" id="cantidad_humidificador" name="cantidad_humidificador" value="1" min="1" max="10" oninput="outputIDcantidad_humidificador.value = cantidad_humidificador.value">
    <output name="salida" id="outputIDcantidad_humidificador"></output>
</div>
<div class="card-footer border-warning">
    <label for="luces">Luces</label>
    <input type="range" id="luces" name="luces" value="1" min="1" max="24" oninput="outputIDluces.value = luces.value">
    <output name="salida" id="outputIDluces"></output>
</div>
<div class="card-footer border-warning">
    <label for="cantidad_luces">Cantidad de luces</label>
    <input type="range" id="cantidad_luces" name="cantidad_luces" value="1" min="1" max="10" oninput="outputIDcantidad_luces.value = cantidad_luces.value">
    <output name="salida" id="outputIDcantidad_luces"></output>
</div>
<div class="card-footer border-warning">
    <label for="ph_negativo">pH negativo</label>
    <input type="range" step="0.1" id="ph_negativo" name="ph_negativo" value="6.0" min="0.1" max="14" oninput="outputIDph_negativo.value = ph_negativo.value">
    <output name="salida" id="outputIDph_negativo"></output>
</div>
<div class="card-footer border-warning">
    <label for="ph_positivo">pH positivo</label>
    <input type="range" step="0.1" id="ph_positivo" name="ph_positivo" value="7.0" min="0.1" max="14" oninput="outputIDph_positivo.value = ph_positivo.value">
    <output name="salida" id="outputIDph_positivo"></output>
</div>
<div class="card-footer border-warning">
    <label for="ec_negativo">EC negativo</label>
    <input type="range" step="0.1" id="ec_negativo" name="ec_negativo" value="0.5" min="0.1" max="1000" oninput="outputIDec_negativo.value = ec_negativo.value">
    <output name="salida" id="outputIDec_negativo"></output>
</div>
<div class="card-footer border-warning">
    <label for="ec_positivo">EC positivo</label>
    <input type="range" step="0.1" id="ec_positivo" name="ec_positivo" value="1.5" min="0.1" max="1000" oninput="outputIDec_positivo.value = ec_positivo.value">
    <output name="salida" id="outputIDec_positivo"></output>
</div>
<div class="card-footer border-warning">
    <button type="submit" class="btn btn-primary">Enviar</button>
</div>
</div>
</form>

{% endblock content %}

src/templates/cambiar_password.html
{% extends 'base.html' %}

{% block title %} Cambiar Password {% endblock title %}

{% block content %}

<style>
 body, html {
  height: 100%;
}

.bg {
  /* The image used */
  background-image: url("../static/cambiarpass.jpg");

  /* Full height */
  height: 100%;

  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}

</style>

<div class="bg">

<div class="modal fade" id="modalRegisterForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <form method="post" action="{{ url_for('users.cambiarpass', username=session['username']) }}" name="RegisterForm">
  {{ form.hidden_tag() }}
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Cambiar Password</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <div class="form-group">
        <div class="md-form mb-4">
          <i class="fas fa-lock prefix grey-text"></i>
          {{ form.old_password(type="password", id="orangeForm-pass", class="form-control validate") }}
          {{ form.old_password.label(for="orangeForm-pass") }}
        </div>
        <div class="md-form mb-4">
          <i class="fas fa-lock prefix grey-text"></i>
          {{ form.password(type="password", id="orangeForm-pass", class="form-control validate") }}
          {{ form.password.label(for="orangeForm-pass") }}
        </div>
        <div class="md-form mb-4">
          <i class="fas fa-lock prefix grey-text"></i>
          {{ form.password_confirm(type="password", id="defaultForm-pass", class="form-control validate") }}
          {{ form.password_confirm.label(for="orangeForm-pass") }}
        </div>
      </div>
      <div class="modal-footer d-flex justify-content-center">
          {{ form.submit(class="btn btn-deep-orange") }}
      </div>
    </div>
    </div>
  </div>
  </form>
</div>

<div class="text-center">
  <h1><a href="" class="btn btn-default btn-rounded mb-4 text-white font-weight-bold" data-toggle="modal" data-target="#modalRegisterForm" id="cp">CAMBIAR PASSWORD</a></h1>
</div>
</div>
{% endblock content %}

src/templates/descarga.html
{% extends 'base.html' %}
{% block title %} Home {% endblock title %}

{% block content %}
 <a href="http://sistemadomotica.dvrdns.org:8888/{{ link }}" class="btn btn-outline-dark" style="font-size: 30px">Descargar Archivo</a>
{% endblock content %}

src/templates/historial.html
{% extends 'base.html' %}

{% block title %} Historial {% endblock title %}

{% block content %}
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Usuario</th>
      <th scope="col">Nombre de Configuracion</th>
      <th scope="col">Fecha y hora</th>
    </tr>
  </thead>
  <tbody>
  {% for h in historial %}
    <tr>

      <td>{{ h.id }}</td>
      <td>{{ h.usuario }}</td>
      <td>{{ h.nombre_conf }}</td>
      <td>{{ h.fecha_hora }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock content %}

src/templates/indoor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RaspControl|INDOOR</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet" type="text/css">
</head>
<body>

<form method="POST">
<div class="card bg-dark mx-auto text-center" style="max-width: 18rem;">

    {{ form.hidden_tag() }}

    {% if ban_luz == False %}

    {{ form.luz(class="botonesON") }}<br><br>

    {% else %}

    {{ form.a_luz(class="botonesOFF") }}<br><br>

    {% endif %}
    {% if ban_ec_down == False %}

    {{ form.ec_down(class="botonesON") }}<br><br>

    {% else %}

    {{ form.a_ec_down(class="botonesOFF") }}<br><br>

    {% endif %}
    {% if ban_ec_up == False %}

    {{ form.ec_up(class="botonesON") }}<br><br>

    {% else %}

    {{ form.a_ec_up(class="botonesOFF") }}<br><br>

    {% endif %}
    {% if ban_hum == False %}

    {{ form.humedad(class="botonesON") }}<br><br>

    {% else %}

    {{ form.a_humedad(class="botonesOFF") }}<br><br>

    {% endif %}
    {% if ban_rie == False %}

    {{ form.riego(class="botonesON") }}<br><br>

    {% else %}

    {{ form.a_riego(class="botonesOFF") }}<br><br>

    {% endif %}
    {% if ban_int_ext == False %}

    {{ form.intractor_extractor(class="botonesON") }}<br><br>

    {% else %}

    {{ form.a_intractor_extractor(class="botonesOFF") }}<br><br>

    {% endif %}
    {% if ban_ph_up == False %}

    {{ form.ph_up(class="botonesON") }}<br><br>

    {% else %}

    {{ form.a_ph_up(class="botonesOFF") }}<br><br>

    {% endif %}
    {% if ban_ph_down == False %}

    {{ form.ph_down(class="botonesON") }}<br><br>

    {% else %}

    {{ form.a_ph_down(class="botonesOFF") }}<br><br>

    {% endif %}
    {{ form.salir(class="botonesOFF") }}


</div>

</form>

</body>
</html>

src/templates/login.html
{% extends 'base.html' %}

{% block title %} Entrar {% endblock title %}

{% block content %}
<div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
    <form method="post" action="{{ url_for('users.login') }}" name="LoginForm">

  {{ form.hidden_tag() }}
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center" style="background-color:#008000">
        <h4 class="modal-title w-100 font-weight-bold">Iniciar sesion</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <div class="md-form mb-5">
          <i class="fas fa-envelope prefix grey-text"></i>
          {{ form.username(type="text", id="orangeForm-name", class="form-control validate") }}
          {{ form.username.label(for="orangeForm-name") }}
        </div>

        <div class="md-form mb-4">
          <i class="fas fa-lock prefix grey-text"></i>
          {{ form.password(type="password", id="defaultForm-pass", class="form-control validate") }}
          {{ form.password.label(for="defaultForm-pass") }}
        </div>

      </div>
      <div class="modal-footer d-flex justify-content-center">
        {{ form.submit(class="btn btn-default") }}
      </div>
    </div>
  </div>
</form>
</div>

<div class="text-center" style="background-color:#008000">
  <h1><a href="" class="btn btn-default btn-rounded mb-4" data-toggle="modal" data-target="#modalLoginForm" id="cp" style="background-color:#44cf44">INICIAR SESION</a></h1>
</div>
<div class="center-block">
  <img src="../static/logo_florabot2.png" alt="FloraBot" width="100%" height="auto">
</div>

{% endblock content %}

src/templates/mensajes.html
{% extends 'base.html' %}

{% block title %} Mensaje al Administrador {% endblock title %}

{% block content %}

<form class="range-field" method="POST">
<div class="card bg-dark mx-auto text-left text-white col-md-8">
Fecha: 2023-06-25 - Hora: 10:30 AM<br>
Número de serie: 1234567890<br>
Usuario: JohnDoe<br>
</div>
<div class="card bg-dark mx-auto text-left text-white col-md-8">
    {{ form.hidden_tag() }}
<div class="card-text border-warning">
    {{ form.asunto.label() }}
    {{ form.asunto(class="col-md-8 mb-10") }}
    {% if form.asunto.errors %}
    {% for error in form.asunto.errors %}

        <div class="alert alert-info alert-dismissible fade show" role="alert">
          <button type="button" class="fade close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>

            {{ error }}
        </div>


    {% endfor %}
    {% endif %}
<div class="card-text border-warning">
    {{ form.mensaje.label() }}
    {{ form.mensaje(class="col-md-8 mb-10", cols="35",rows="20") }}
    {% if form.mensaje.errors %}
    {% for error in form.mensaje.errors %}

        <div class="alert alert-info alert-dismissible fade show" role="alert">
          <button type="button" class="fade close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>

            {{ error }}
        </div>


    {% endfor %}
    {% endif %}
<div class="card-footer border-warning">
    {{ form.submit(class="btn btn-success mb-2 t-2") }}
</div>
</div>
</div>
</div>
</form>
{% for msj in listado %}
{% if msj.respuesta == None %}
<div class="jumbotronchat text-white" style="background-color:rgba(68, 33, 77, 0.7); border:3px solid Grey;">
  <p style="background-color:rgba(68, 33, 77, 0.5);">Tu mensaje es el siguiente {{ msj.usuario }}:
      <br>
  Asunto: Solicitud de información<br>
  Mensaje: Hola, me gustaría obtener más información sobre el sistema de riego automático.
  </p>
  <hr class="my-10">

  <p class="lead" style="background-color:rgba(201, 24, 48, 1);">Sin respuesta:
      <br>

   </p>
    <span style="background-color:rgba(68, 33, 77, 0.5);">Fecha: 2023-06-24 - Hora: 09:45 AM</span>
</div>
  <hr class="my-10">
    {% else %}
<div class="jumbotronchat text-white" style="background-color:rgba(68, 33, 77, 0.7); border:3px solid Grey;">
  <p style="background-color:rgba(68, 33, 77, 0.5);">Tu mensaje es el siguiente {{ msj.usuario }}:
      <br>
  Asunto: Solicitud de información<br>
  Mensaje: Hola, me gustaría obtener más información sobre el sistema de riego automático.
  </p>
  <hr class="my-10">

  <p class="lead" style="background-color:rgba(0, 173, 38, 0.5);">La respuesta del Administrador:
      <br>
    Gracias por tu interés en nuestro sistema de riego automático. Te enviaremos la información detallada por correo electrónico.
   </p>
    <span style="background-color:rgba(68, 33, 77, 0.5);">Fecha: 2023-06-24 - Hora: 10:15 AM</span>
</div>
  <hr class="my-10">
    {% endif %}
{% endfor %}


{% endblock content %}

src/templates/register.html
{% extends 'base.html' %}

{% block title %} Registrar usuario {% endblock title %}

{% block content %}

<div class="modal fade" id="modalRegisterForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <form method="post" action="{{ url_for('users.register') }}" name="RegisterForm">
  {{ form.hidden_tag() }}
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Registrar Usuario</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <div class="form-group">
        <div class="md-form mb-5">
          <i class="fas fa-user prefix grey-text"></i>
          {{ form.username(type="text", id="orangeForm-name", class="form-control validate") }}
          {{ form.username.label(for="orangeForm-name") }}
        </div>
        <div class="md-form mb-4">
          <i class="fas fa-lock prefix grey-text"></i>
          {{ form.password(type="password", id="orangeForm-pass", class="form-control validate") }}
          {{ form.password.label(for="orangeForm-pass") }}
        </div>
        <div class="md-form mb-4">
          <i class="fas fa-lock prefix grey-text"></i>
          {{ form.password_confirm(type="password", id="defaultForm-pass", class="form-control validate") }}
          {{ form.password_confirm.label(for="orangeForm-pass") }}
        </div>
      </div>
      <div class="modal-footer d-flex justify-content-center">

          {{ form.submit(class="btn btn-deep-orange") }}

      </div>
    </div>
    </div>
  </div>
  </form>
</div>

<div class="text-center">
  <h1><a href="" class="btn btn-default btn-rounded mb-4" data-toggle="modal" data-target="#modalRegisterForm">REGISTRAR USUARIO</a></h1>
</div>

{% endblock content %}

src/templates/stdout.html
{% extends 'comando.html' %}

{% block stdout %}

<h1>-------------------------------</h1>
{% for line in stdout %}


<p>{{ line.strip('\n') }}</p>

{% endfor %}
<h1>-------------------------------</h1>

{% endblock stdout %}

src/templates/userslist.html
{% extends 'base.html' %}

{% block title %} Lista de Usuarios {% endblock title %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Borrar usuarios</h1>
    <p class="lead">Seleccione el usuario que desea borrar</p>
  </div>

{% for user in users %}
<div class="list-group">
  <a href="{{ url_for('users.delete', userid=user.id) }}" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">{{ user.username }}</h5>
      <small>3 days ago</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small>Donec id elit non mi porta.</small>
  </a>
</div>
{% endfor %}

</div>
{% endblock content %}